# Generated by Django 4.1.7 on 2023-12-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=1000)),
                ('lang_from', models.CharField(max_length=10)),
                ('lang_to', models.CharField(max_length=10)),
                ('meanings', models.TextField()),
                ('collins', models.IntegerField()),
                ('oxford', models.IntegerField()),
                ('frequency', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordPronounce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100, null=True)),
                ('soundmark', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='wordpronounce',
            index=models.Index(fields=['word'], name='WordPronounce_word_idx'),
        ),
        migrations.AddIndex(
            model_name='ecdict',
            index=models.Index(fields=['word'], name='WordDefinition_word_idx'),
        ),
    ]
