# Generated by Django 4.1.7 on 2023-12-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collins', models.IntegerField()),
                ('oxford', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ecdict',
            name='collins',
        ),
        migrations.RemoveField(
            model_name='ecdict',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='ecdict',
            name='oxford',
        ),
    ]
