# Generated by Django 4.1.7 on 2023-12-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_wordscore_remove_ecdict_collins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordscore',
            name='word',
            field=models.CharField(default='a', max_length=1000),
            preserve_default=False,
        ),
    ]
