# Generated by Django 4.1.7 on 2023-12-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_wordscore_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=100)),
                ('lang_from', models.CharField(max_length=10)),
                ('lang_to', models.CharField(max_length=10)),
                ('meanings', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ecdict',
        ),
        migrations.AddIndex(
            model_name='worddefinition',
            index=models.Index(fields=['word'], name='WordDefinition_word_idx'),
        ),
    ]
