# Generated by Django 4.1.7 on 2023-12-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_worddefinition_delete_ecdict_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='worddefinition',
            index=models.Index(fields=['source', 'word'], name='WordDefinition_source_word'),
        ),
    ]
