# Generated by Django 4.1.7 on 2023-12-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_worddefinition_worddefinition_source_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordscore',
            name='collins',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wordscore',
            name='frequency',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wordscore',
            name='oxford',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wordscore',
            name='score',
            field=models.FloatField(),
        ),
    ]
