# Generated by Django 5.0 on 2023-12-27 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_alter_wordscore_collins_alter_wordscore_frequency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worddefinition',
            old_name='lang_from',
            new_name='fromLanguage',
        ),
        migrations.RenameField(
            model_name='worddefinition',
            old_name='lang_to',
            new_name='toLanguage',
        ),
    ]
