# Generated by Django 5.0 on 2024-01-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_rename_lang_from_worddefinition_fromlanguage_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='worddefinition',
            constraint=models.UniqueConstraint(fields=('word', 'source', 'fromLanguage', 'toLanguage'), name='WordDefinition_unique'),
        ),
    ]
