# Generated by Django 5.0 on 2024-01-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_worddefinition_worddefinition_unique'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wordscore',
            index=models.Index(fields=['word', 'score'], name='WordScore_word_score'),
        ),
    ]
