# Generated by Django 5.0 on 2024-01-02 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_wordscore_wordscore_word_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordscore',
            options={'ordering': ['-score']},
        ),
    ]
