# Generated by Django 4.1.7 on 2024-01-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_wordsoundmark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordpronounce',
            name='pronounceBase64',
        ),
        migrations.AddField(
            model_name='wordpronounce',
            name='pronounce',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
