# Generated by Django 4.1.7 on 2023-04-01 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecdict',
            fields=[
                ('word', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('meanings', models.TextField()),
                ('collins', models.IntegerField()),
                ('oxford', models.IntegerField()),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GlossaryBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('bookName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('date', models.BigIntegerField()),
                ('uuid', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=1000)),
                ('bookName', models.CharField(max_length=100)),
                ('answer', models.IntegerField()),
                ('studyTime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MissingWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=10)),
                ('lastUpdate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=100)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WordDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=10)),
                ('meanings', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WordPronounce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100, null=True)),
                ('soundmark', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=10)),
                ('searchSource', models.CharField(max_length=100)),
                ('definitionSources', models.CharField(max_length=1000)),
                ('exerciseBook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_exerciseBook', to='api.glossarybooks')),
                ('glossaryBook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_defaultBookName', to='api.glossarybooks')),
            ],
        ),
        migrations.CreateModel(
            name='GlossaryWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=1000)),
                ('addDate', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.glossarybooks')),
            ],
        ),
    ]
