# Generated by Django 4.1.4 on 2023-03-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_worddefinition_meanings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossarywords',
            name='word',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='history',
            name='word',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='missingword',
            name='word',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='wordannotation',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wordannotation',
            name='word',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='meanings',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='word',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='wordpronounce',
            name='word',
            field=models.CharField(max_length=1000),
        ),
    ]
