# Generated by Django 4.1.7 on 2023-12-26 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('bookName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GlossaryWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=1000)),
                ('addDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=100)),
                ('uuid', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=1000)),
                ('bookName', models.CharField(max_length=100)),
                ('answer', models.IntegerField()),
                ('studyTime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDefinedWordMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=1000)),
                ('meaning', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDefinedWordNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=1000)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=10)),
                ('searchSource', models.CharField(max_length=100)),
                ('definitionSources', models.CharField(max_length=1000)),
                ('exerciseBook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_exerciseBook', to='userData.glossarybooks')),
                ('glossaryBook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_defaultBookName', to='userData.glossarybooks')),
            ],
        ),
        migrations.AddIndex(
            model_name='userdefinedwordnote',
            index=models.Index(fields=['user', 'word'], name='UDWN_user_word'),
        ),
        migrations.AddIndex(
            model_name='userdefinedwordmeaning',
            index=models.Index(fields=['user', 'word'], name='UDWM_user_word'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['user', 'uuid'], name='History_user_uuid'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['user', 'created'], name='History_user_created'),
        ),
        migrations.AddField(
            model_name='glossarywords',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userData.glossarybooks'),
        ),
    ]
