# Generated by Django 5.0 on 2023-12-27 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='searchSource',
            new_name='searchSources',
        ),
    ]
