# Generated by Django 5.0 on 2023-12-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0002_rename_searchsource_userinfo_searchsources'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='primaryLanguage',
            field=models.CharField(default='zh', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='searchLanguage',
            field=models.CharField(default='zh', max_length=10),
            preserve_default=False,
        ),
    ]
