# Generated by Django 5.0 on 2023-12-27 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0003_userinfo_primarylanguage_userinfo_searchlanguage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glossarywords',
            name='addDate',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='language',
        ),
        migrations.AddField(
            model_name='glossarywords',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glossarywords',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='exerciseBook',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='glossaryBook',
            field=models.CharField(max_length=100),
        ),
    ]
