# Generated by Django 5.0 on 2023-12-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0004_remove_glossarywords_adddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glossarywords',
            name='book',
        ),
        migrations.AddField(
            model_name='glossarywords',
            name='bookName',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
