# Generated by Django 5.0 on 2023-12-28 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0005_remove_glossarywords_book_glossarywords_bookname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glossarywords',
            name='bookName',
        ),
        migrations.AddField(
            model_name='glossarywords',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userData.glossarybooks'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='glossarybooks',
            index=models.Index(fields=['user', 'bookName'], name='GB_user_bookName'),
        ),
    ]
