# Generated by Django 5.0 on 2024-01-02 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0007_remove_history_studytime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='searchLanguage',
            new_name='displayLanguage',
        ),
    ]
