# Generated by Django 5.0 on 2024-01-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0008_rename_searchlanguage_userinfo_displaylanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefinedWordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=10)),
                ('data', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserDefinedWordMeaning',
        ),
        migrations.DeleteModel(
            name='UserDefinedWordNote',
        ),
        migrations.AddIndex(
            model_name='userdefinedworddata',
            index=models.Index(fields=['user', 'word'], name='UDWM_user_word'),
        ),
    ]
