# Generated by Django 5.0 on 2024-01-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0009_userdefinedworddata_delete_userdefinedwordmeaning_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userdefinedworddata',
            constraint=models.UniqueConstraint(fields=('user', 'word', 'type'), name='UDWM_user_word_type'),
        ),
    ]
